# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec28e44d40e5dd787bb834a60effadbb1f370bfae8accfffc76a6160b39a7bfe4081016a867ba6e8237dd67ccabcb14aa50ebebafcd68c8103b733e8e7f57ded

test:
  secret_key_base: 5f61a0b6501b085bda78a688d27b71517d9172376a2961e04f3e28b5a60218c01d6b837f50f442ecf7d04e0d8aa33f23b24b9200b83f27fad3f08280f5dab58b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
